/* libcmatrix-1.0.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "Cm", gir_namespace = "CM", gir_version = "0", lower_case_cprefix = "cm_")]
namespace Cm {
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_account_get_type ()")]
	public class Account : Cm.User {
		[CCode (has_construct_function = false)]
		protected Account ();
		public async bool delete_3pid_async (string value, string type, GLib.Cancellable? cancellable) throws GLib.Error;
		[CCode (async_result_pos = 3.1)]
		public async bool get_3pids_async (GLib.Cancellable? cancellable, out GLib.GenericArray<string> emails, out GLib.GenericArray<string> phones) throws GLib.Error;
		public unowned string? get_login_id ();
		public async bool set_display_name_async (string name, GLib.Cancellable? cancellable) throws GLib.Error;
		public bool set_login_id (string login_id);
		public async bool set_user_avatar_async (GLib.File image_file, GLib.Cancellable? cancellable) throws GLib.Error;
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_client_get_type ()")]
	public class Client : GLib.Object {
		[CCode (has_construct_function = false)]
		public Client ();
		[Version (since = "0.0.1")]
		public async bool add_pusher_async (Cm.Pusher pusher, GLib.Cancellable? cancellable) throws GLib.Error;
		[Version (since = "0.0.1")]
		public bool add_pusher_sync (Cm.Pusher pusher, GLib.Cancellable? cancellable = null) throws GLib.Error;
		public bool can_connect ();
		public unowned string? get_access_token ();
		public unowned Cm.Account get_account ();
		public unowned string? get_device_id ();
		public unowned string? get_device_name ();
		public unowned string get_ed25519_key ();
		public bool get_enabled ();
		public unowned string? get_homeserver ();
		public async unowned string get_homeserver_async (GLib.Cancellable? cancellable) throws GLib.Error;
		[CCode (array_length = false, array_null_terminated = true)]
		[Version (since = "0.0.3")]
		public unowned string[]? get_homeserver_versions ();
		public unowned GLib.ListModel get_invited_rooms ();
		public unowned GLib.ListModel get_joined_rooms ();
		public unowned GLib.ListModel get_key_verifications ();
		public bool get_logged_in ();
		public bool get_logging_in ();
		public unowned string get_password ();
		public unowned string get_pickle_key ();
		[Version (since = "0.0.1")]
		public async GLib.GenericArray<Cm.Pusher> get_pushers_async (GLib.Cancellable? cancellable) throws GLib.Error;
		[Version (since = "0.0.1")]
		public GLib.GenericArray<Cm.Pusher> get_pushers_sync (GLib.Cancellable? cancellable = null) throws GLib.Error;
		public unowned GLib.RefString get_user_id ();
		public bool is_sync ();
		public async bool join_room_async (string id_or_alias, GLib.Cancellable? cancellable) throws GLib.Error;
		[Version (since = "0.0.2")]
		public bool join_room_sync (string id_or_alias) throws GLib.Error;
		[Version (since = "0.0.1")]
		public async bool remove_pusher_async (Cm.Pusher pusher, GLib.Cancellable? cancellable) throws GLib.Error;
		[Version (since = "0.0.1")]
		public bool remove_pusher_sync (Cm.Pusher pusher, GLib.Cancellable? cancellable = null) throws GLib.Error;
		public void set_access_token (string? access_token);
		public void set_device_id (string device_id);
		public void set_device_name (string device_name);
		public void set_enabled (bool enable);
		public bool set_homeserver (string homeserver);
		public void set_password (string password);
		public void set_pickle_key (string pickle_key);
		public void set_sync_callback (owned Cm.Callback? callback);
		public bool set_user_id (string matrix_user_id);
		public void start_sync ();
		public void stop_sync ();
		[NoAccessorMethod]
		public string home_server { set construct; }
		public signal void status_changed ();
	}
	[CCode (cheader_filename = "CM-0.h", has_type_id = false)]
	[Compact]
	public class Db {
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_event_get_type ()")]
	public class Event : GLib.Object {
		[CCode (has_construct_function = false)]
		protected Event ();
		[NoWrapper]
		public virtual void* generate_json (void* room);
		[NoWrapper]
		public virtual string get_api_url (void* room);
		public unowned string get_id ();
		public Cm.EventType get_m_type ();
		public unowned Cm.User get_sender ();
		public Cm.EventState get_state ();
		public int64 get_time_stamp ();
		public bool is_encrypted ();
		public signal void updated ();
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_matrix_get_type ()")]
	public class Matrix : GLib.Object {
		[CCode (has_construct_function = false)]
		public Matrix (string data_dir, string cache_dir, string app_id, bool disable_auto_login);
		public async bool add_clients_async (GLib.GenericArray<Secret.Retrievable> secrets) throws GLib.Error;
		public Cm.Client client_new ();
		public async bool delete_client_async (Cm.Client client, GLib.Cancellable? cancellable) throws GLib.Error;
		public unowned GLib.ListModel get_clients_list ();
		public bool has_client_with_id (string user_id);
		public bool is_ready ();
		public async bool open_async (string db_path, string db_name, GLib.Cancellable? cancellable) throws GLib.Error;
		public async bool save_client_async (Cm.Client client, GLib.Cancellable? cancellable) throws GLib.Error;
		[Version (since = "0.0.2")]
		public bool save_client_sync (Cm.Client client, GLib.Cancellable? cancellable = null) throws GLib.Error;
		[NoAccessorMethod]
		public bool ready { get; }
	}
	[CCode (cheader_filename = "CM-0.h", has_type_id = false)]
	[Compact]
	public class Olm {
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_pusher_get_type ()")]
	[Version (since = "0.0.1")]
	public class Pusher : GLib.Object {
		[CCode (has_construct_function = false)]
		public Pusher ();
		public async bool check_valid (GLib.Cancellable? cancellable) throws GLib.Error;
		public unowned string get_app_display_name ();
		public unowned string get_app_id ();
		public unowned string get_device_display_name ();
		public Cm.PusherKind get_kind ();
		public unowned string get_kind_as_string ();
		public unowned string get_lang ();
		public unowned string get_profile_tag ();
		public unowned string get_pushkey ();
		public unowned string get_url ();
		public void set_app_display_name (string app_display_name);
		public void set_app_id (string app_id);
		public void set_device_display_name (string device_display_name);
		public void set_kind (Cm.PusherKind kind);
		public void set_kind_from_string (string kind);
		public void set_lang (string lang);
		public void set_profile_tag (string profile_tag);
		public void set_pushkey (string pushkey);
		public void set_url (string url);
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_room_get_type ()")]
	public class Room : GLib.Object {
		[CCode (has_construct_function = false)]
		protected Room ();
		public async bool accept_invite_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public async bool enable_encryption_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public async GLib.InputStream get_avatar_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public async Cm.Event get_event_async (string event_id, GLib.Cancellable? cancellable) throws GLib.Error;
		public Cm.Event get_event_sync (string event_id, GLib.Cancellable? cancellable = null) throws GLib.Error;
		public unowned GLib.ListModel get_events_list ();
		public unowned string get_id ();
		public unowned GLib.ListModel get_joined_members ();
		public unowned string? get_name ();
		public unowned string? get_past_name ();
		public unowned string get_room_version ();
		[Version (since = "0.0.2")]
		public unowned string? get_topic ();
		public int64 get_unread_notification_counts ();
		public bool is_encrypted ();
		public async bool leave_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public async bool load_past_events_async () throws GLib.Error;
		[Version (since = "0.0.2")]
		public bool load_past_events_sync () throws GLib.Error;
		public async bool reject_invite_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public bool self_has_power_for_event (Cm.EventType type);
		public async string send_file_async (GLib.File file, string body, [CCode (delegate_target_pos = 3.5, scope = "async")] GLib.FileProgressCallback progress_callback, GLib.Cancellable? cancellable) throws GLib.Error;
		public async string send_text_async (string text, GLib.Cancellable? cancellable) throws GLib.Error;
		public async bool set_read_marker_async (Cm.Event fully_read_event, Cm.Event read_receipt_event) throws GLib.Error;
		public async bool set_typing_notice_async (bool typing, GLib.Cancellable? cancellable) throws GLib.Error;
		[NoAccessorMethod]
		public string encrypted { owned get; }
		public string name { get; }
		[NoAccessorMethod]
		[Version (since = "0.0.2")]
		public int unread_count { get; }
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_room_event_get_type ()")]
	public class RoomEvent : Cm.Event {
		[CCode (has_construct_function = false)]
		protected RoomEvent ();
		public unowned Cm.Room get_room ();
		public unowned string get_room_version ();
	}
	[CCode (cheader_filename = "CM-0.h", has_type_id = false)]
	[Compact]
	public class RoomMember {
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_room_message_event_get_type ()")]
	public class RoomMessageEvent : Cm.RoomEvent {
		[CCode (has_construct_function = false)]
		protected RoomMessageEvent ();
		public unowned string get_body ();
		public async GLib.InputStream get_file_async (GLib.Cancellable? cancellable, [CCode (scope = "async")] GLib.FileProgressCallback progress_callback) throws GLib.Error;
		public unowned string get_file_path ();
		public Cm.ContentType get_msg_type ();
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_user_get_type ()")]
	public class User : GLib.Object {
		[CCode (has_construct_function = false)]
		protected User ();
		public async GLib.InputStream get_avatar_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public unowned string get_avatar_url ();
		public unowned string? get_display_name ();
		public unowned GLib.RefString get_id ();
		public async bool load_info_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public signal void changed ();
	}
	[CCode (cheader_filename = "CM-0.h", has_type_id = false)]
	[Compact]
	public class UserList {
	}
	[CCode (cheader_filename = "CM-0.h", type_id = "cm_verification_event_get_type ()")]
	public class VerificationEvent : Cm.Event {
		[CCode (has_construct_function = false)]
		protected VerificationEvent ();
		public async bool cancel_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public async bool continue_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public async bool match_async (GLib.Cancellable? cancellable) throws GLib.Error;
	}
	[CCode (cheader_filename = "CM-0.h", cprefix = "CM_CONTENT_TYPE_", type_id = "cm_content_type_get_type ()")]
	public enum ContentType {
		UNKNOWN,
		TEXT,
		EMOTE,
		NOTICE,
		IMAGE,
		FILE,
		LOCATION,
		AUDIO,
		VIDEO,
		SERVER_NOTICE
	}
	[CCode (cheader_filename = "CM-0.h", cprefix = "CM_EVENT_STATE_", type_id = "cm_event_state_get_type ()")]
	public enum EventState {
		UNKNOWN,
		DRAFT,
		WAITING,
		SENDING,
		SENDING_FAILED,
		SENT,
		RECEIVED
	}
	[CCode (cheader_filename = "CM-0.h", cprefix = "CM_M_", type_id = "cm_event_type_get_type ()")]
	public enum EventType {
		UNKNOWN,
		CALL_ANSWER,
		CALL_ASSERTED_IDENTITY,
		CALL_ASSERTED_IDENTITY_PREFIX,
		CALL_CANDIDATES,
		CALL_HANGUP,
		CALL_INVITE,
		CALL_NEGOTIATE,
		CALL_REJECT,
		CALL_REPLACES,
		CALL_SELECT_ANSWER,
		DIRECT,
		DUMMY,
		FORWARDED_ROOM_KEY,
		FULLY_READ,
		IGNORED_USER_LIST,
		KEY_VERIFICATION_ACCEPT,
		KEY_VERIFICATION_CANCEL,
		KEY_VERIFICATION_DONE,
		KEY_VERIFICATION_KEY,
		KEY_VERIFICATION_MAC,
		KEY_VERIFICATION_READY,
		KEY_VERIFICATION_REQUEST,
		KEY_VERIFICATION_START,
		PRESENCE,
		PUSH_RULES,
		REACTION,
		RECEIPT,
		ROOM_ALIASES,
		ROOM_AVATAR,
		ROOM_BOT_OPTIONS,
		ROOM_CANONICAL_ALIAS,
		ROOM_CREATE,
		ROOM_ENCRYPTED,
		ROOM_ENCRYPTION,
		ROOM_GUEST_ACCESS,
		ROOM_HISTORY_VISIBILITY,
		ROOM_JOIN_RULES,
		ROOM_KEY,
		ROOM_KEY_REQUEST,
		ROOM_MEMBER,
		ROOM_MESSAGE,
		ROOM_MESSAGE_FEEDBACK,
		ROOM_NAME,
		ROOM_PINNED_EVENTS,
		ROOM_PLUMBING,
		ROOM_POWER_LEVELS,
		ROOM_REDACTION,
		ROOM_RELATED_GROUPS,
		ROOM_SERVER_ACL,
		ROOM_THIRD_PARTY_INVITE,
		ROOM_TOMBSTONE,
		ROOM_TOPIC,
		SECRET_REQUEST,
		SECRET_SEND,
		SECRET_STORAGE_DEFAULT_KEY,
		SPACE_CHILD,
		SPACE_PARENT,
		STICKER,
		TAG,
		TYPING,
		USER_STATUS,
		ROOM_INVITE,
		ROOM_BAN,
		ROOM_KICK
	}
	[CCode (cheader_filename = "CM-0.h", cprefix = "CM_PUSHER_KIND_", has_type_id = false)]
	public enum PusherKind {
		UNKNOWN,
		HTTP,
		EMAIL
	}
	[CCode (cheader_filename = "CM-0.h", cprefix = "CM_STATUS_", type_id = "cm_status_get_type ()")]
	public enum Status {
		UNKNOWN,
		JOIN,
		LEAVE,
		INVITE,
		BAN,
		KNOCK
	}
	[CCode (cheader_filename = "CM-0.h", cprefix = "CM_ERROR_", type_id = "cm_error_get_type ()")]
	public errordomain Error {
		FORBIDDEN,
		UNKNOWN_TOKEN,
		MISSING_TOKEN,
		BAD_JSON,
		NOT_JSON,
		NOT_FOUND,
		LIMIT_EXCEEDED,
		UNKNOWN,
		UNRECOGNIZED,
		UNAUTHORIZED,
		USER_DEACTIVATED,
		USER_IN_USE,
		INVALID_USERNAME,
		ROOM_IN_USE,
		INVALID_ROOM_STATE,
		THREEPID_IN_USE,
		THREEPID_NOT_FOUND,
		THREEPID_AUTH_FAILED,
		THREEPID_DENIED,
		SERVER_NOT_TRUSTED,
		UNSUPPORTED_ROOM_VERSION,
		INCOMPATIBLE_ROOM_VERSION,
		BAD_STATE,
		GUEST_ACCESS_FORBIDDEN,
		CAPTCHA_NEEDED,
		CAPTCHA_INVALID,
		MISSING_PARAM,
		INVALID_PARAM,
		TOO_LARGE,
		EXCLUSIVE,
		RESOURCE_LIMIT_EXCEEDED,
		CANNOT_LEAVE_SERVER_NOTICE_ROOM,
		BAD_PASSWORD,
		NO_HOME_SERVER,
		BAD_HOME_SERVER,
		USER_DEVICE_CHANGED,
		BAD_PUSH_GATEWAY;
		public static GLib.Quark quark ();
	}
	[CCode (cheader_filename = "CM-0.h", instance_pos = 4.9)]
	public delegate void Callback (Cm.Client self, Cm.Room? room, GLib.GenericArray<Cm.Event> events, GLib.Error? err);
	[CCode (cheader_filename = "CM-0.h")]
	[Version (replacement = "Error.quark")]
	public static GLib.Quark error_quark ();
	[CCode (cheader_filename = "CM-0.h")]
	public static void init (bool init_gcrypt);
	[CCode (cheader_filename = "CM-0.h")]
	[Version (since = "0.0.2")]
	public static async string? utils_get_homeserver_async (string username, uint timeout, GLib.Cancellable? cancellable) throws GLib.Error;
	[CCode (cheader_filename = "CM-0.h")]
	[Version (since = "0.0.2")]
	public static string? utils_get_homeserver_sync (string username) throws GLib.Error;
}
